#include "code-generation/NodeVisitorCodeGen.h"

void NodeVisitorCodeGen::visitId(Id *) {}
void NodeVisitorCodeGen::visitConstructList(ConstructList *) {}
void NodeVisitorCodeGen::visitExpr(Expr *) {}
void NodeVisitorCodeGen::visitAlExpr(AlExpr *) {}
void NodeVisitorCodeGen::visitExprParen(ExprParen *) {}
void NodeVisitorCodeGen::visitRelExpr(RelExpr *) {}
void NodeVisitorCodeGen::visitAlBinExpr(AlBinExpr *) {}
void NodeVisitorCodeGen::visitAlUnExpr(AlUnExpr *) {}
void NodeVisitorCodeGen::visitLitExprString(LitExpr<std::string> *) {}
void NodeVisitorCodeGen::visitLitExprInt(LitExpr<int> *) {}
void NodeVisitorCodeGen::visitAccessOperation(AccessOperation *) {}
void NodeVisitorCodeGen::visitBrackAccess(BracketAccess *) {}
void NodeVisitorCodeGen::visitDotAccess(DotAccess *) {}
void NodeVisitorCodeGen::visitVar(Var *) {}
void NodeVisitorCodeGen::visitFunctionCallExpr(FunctionCallExpr *) {}
void NodeVisitorCodeGen::visitStmt(Stmt *) {}
void NodeVisitorCodeGen::visitAssignStmt(AssignStmt *) {}
void NodeVisitorCodeGen::visitFunctionCallStmt(FunctionCallStmt *) {}
void NodeVisitorCodeGen::visitReadStmt(ReadStmt *) {}
void NodeVisitorCodeGen::visitPrintStmt(PrintStmt *) {}
void NodeVisitorCodeGen::visitCase(Case *) {}
void NodeVisitorCodeGen::visitSwitchStmt(SwitchStmt *) {}
void NodeVisitorCodeGen::visitWhileStmt(WhileStmt *) {}
void NodeVisitorCodeGen::visitForStmt(ForStmt *) {}
void NodeVisitorCodeGen::visitElsePart(ElsePart *) {}
void NodeVisitorCodeGen::visitElse(Else *) {}
void NodeVisitorCodeGen::visitIfStmt(IfStmt *) {}
void NodeVisitorCodeGen::visitElseIf(ElseIf *) {} 
void NodeVisitorCodeGen::visitReturnStmt(ReturnStmt *) {}
void NodeVisitorCodeGen::visitType(Type *) {}
void NodeVisitorCodeGen::visitVarDeclId(VarDeclId *) {}
void NodeVisitorCodeGen::visitVarInit(VarInit *) {}
void NodeVisitorCodeGen::visitFieldDeclVar(FieldDeclVar *) {}
void NodeVisitorCodeGen::visitFieldDecl(FieldDecl *) {}
void NodeVisitorCodeGen::visitDecls(Decls *) {}
void NodeVisitorCodeGen::visitFormalParams(FormalParams *) {}
void NodeVisitorCodeGen::visitBlock(Block *) {}
void NodeVisitorCodeGen::visitMethodReturnType(MethodReturnType *) {}
void NodeVisitorCodeGen::visitMethodDecl(MethodDecl *) {}
void NodeVisitorCodeGen::visitClassBody(ClassBody *) {}
void NodeVisitorCodeGen::visitClassDecl(ClassDecl *) {}
void NodeVisitorCodeGen::visitProgram(Program *) {}
void NodeVisitorCodeGen::visitExprVarInit(ExprVarInit *) {}
void NodeVisitorCodeGen::visitArrayInitVarInit(ArrayInitVarInit *) {}
void NodeVisitorCodeGen::visitArrayCreation(ArrayCreation *) {}
void NodeVisitorCodeGen::visitArrayCreationVarInit(ArrayCreationVarInit *) {}

